### PR TITLE
build hadoop-3.3.6 on win11 64,vs2022,jdk8_271

### PR DESCRIPTION
**Pull request by haijialiu**
I just test help connect to remote hbase(success)

### CODE REVIEW

**Comment by luanchao19990** [comment]
Thank you for your email.We’ll disposal and reply as soon as possible~Best Wishes~

**Comment by MaHe666** [comment]
Does the hadoop-3.3.6/bin work? I'd like to use it.

**Comment by luanchao19990** [comment]
Thank you for your email.We’ll disposal and reply as soon as possible~Best Wishes~

**Review by cdarlint — APPROVED** [review]

**Comment by luanchao19990** [comment]
Thank you for your email.We’ll disposal and reply as soon as possible~Best Wishes~

**Pull request merged**
